import * as P from '../src/core/project.ts';
import { ChatSession, BROWSER_PREAMBLE } from '../src/core/chat.ts';
import { Ev } from '../src/core/sessions.ts';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
let fails = 0;
const must = (l: string, c: boolean) => { console.log(c ? `✓ ${l}` : `✗ ${l}`); if (!c) fails++; };
const repo = mkdtempSync(join(tmpdir(), 'tai-br-'));
const p = await P.createProject('loja', repo);
const api = await P.addAgent(p, 'api');
const b = await P.addBrowser(p, 'hidden');
const cfg = JSON.parse(await Bun.file(join(repo, '.mcp.json')).text());
must('browser grava o playwright no .mcp.json apontando para o Chrome do anthive', cfg.mcpServers.playwright.args.includes('@playwright/mcp@latest') && cfg.mcpServers.playwright.args.includes('--cdp-endpoint') && cfg.mcpServers.playwright.args.includes(`http://127.0.0.1:${b.port}`));
must('item nasce oculto, com porta própria', b.mode === 'hidden' && b.port >= 9222);
must('segundo browser reaproveita o primeiro', (await P.addBrowser(p, 'hidden')).id === b.id);
const b2 = await P.addBrowser(p, 'window');
must('pedir de novo em outro modo só troca o modo', b2.id === b.id && b2.mode === 'window' && b2.port === b.port);
must('sem ligação, o agent não tem browser', !(await P.agentHasBrowser(p.id, api.id)));
await P.link(p.id, api.id, b.id);
must('ligado, tem', await P.agentHasBrowser(p.id, api.id) && (await P.browserOf(p.id, api.id))?.id === b.id);
const argv = new ChatSession({ cwd: repo, browser: true }, () => {}).argv();
must('chat ligado autoriza mcp__playwright', argv.includes('mcp__playwright'));
must('instructs the agent: snapshot first, refs, never close', argv.some((a) => a.includes('browser_snapshot') && a.includes('browser_close')));
must('sem browser, nada disso entra', !new ChatSession({ cwd: repo }, () => {}).argv().includes('mcp__playwright'));
must('primeiro turno idem', P.firstTurnPlan(api, 'x', false, true)[0]!.includes('mcp__playwright') && !P.firstTurnPlan(api, 'x', false, false)[0]!.includes('mcp__playwright'));
const ev = (o: Partial<Ev>): Ev => ({ uuid: crypto.randomUUID(), parent: null, sidechain: false, type: 'assistant', ts: 0, role: 'assistant', text: '', ...o });
const nav = ev({ tool: 'browser_navigate', input: { url: 'https://loja.dev/pedidos' } });
const snap = ev({ tool: 'browser_snapshot', input: {} });
const evs = [nav, ev({ type: 'user', role: 'user', resultFor: nav.uuid, result: '- Page URL: https://loja.dev/pedidos\n- Page Title: Pedidos' }), snap,
  ev({ type: 'user', role: 'user', resultFor: snap.uuid, result: '- Page URL: https://loja.dev/pedidos\n- Page Title: Pedidos\n- Page Snapshot:\n```yaml\n- heading "Pedidos" [ref=e1]\n```' })];
const st = P.browserStateFrom(evs, { url: '', title: '', snapshot: '', console: '', busy: false });
must('estado do browser sai dos eventos: url, título, snapshot', st.url === 'https://loja.dev/pedidos' && st.title === 'Pedidos' && st.snapshot.includes('[ref=e1]') && st.lastTool === 'browser_snapshot' && !st.busy);
const v = await P.view(p);
must('browser é nó do projeto ligado ao agente', v.nodes.some((n) => n.kind === 'browser') && v.edges.some((e) => e.from === api.id && e.to === b.id));
console.log(fails ? `\n${fails} falha(s)` : '\ntudo verde');
process.exit(fails ? 1 : 0);
