/** Deep search for real (costs a few cents): a haiku agent researches a question that needs the repo, the hive and the web. */
import { mkdtempSync, realpathSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import * as P from '../src/core/project.ts';
import * as store from '../src/core/store.ts';
import { ChatSession, ChatEvent, deepPrompt } from '../src/core/chat.ts';
let fails = 0;
const must = (l: string, c: boolean) => { console.log(c ? `✓ ${l}` : `✗ ${l}`); if (!c) fails++; };
const cwd = realpathSync(mkdtempSync(join(tmpdir(), 'tai-deep-')));
writeFileSync(join(cwd, 'README.md'), '# widget\n\nThe widget speaks the FROBNICATE protocol v3 over port 7331; every message carries a frob-id so retries are idempotent.\n');
writeFileSync(join(cwd, 'CLAUDE.md'), '# CLAUDE.md\n\nSmall repo: README.md is the spec.\n');
const sh = (c: string[]) => Bun.spawnSync(c, { cwd, stdout: 'ignore', stderr: 'ignore' });
sh(['git', 'init', '-q']); sh(['git', 'add', '-A']); sh(['git', 'commit', '-qm', 'frobnicate v3']);
const p = await P.createProject('widget', cwd);
await P.ensureBus(cwd);
const api = await P.addAgent(p, 'api');
await store.create({ kind: 'note', title: 'why-frobnicate', body: 'FROBNICATE v3 was chosen for idempotent retries; v2 duplicated messages.\n', acl: ['api'], project: p.id });
const events: ChatEvent[] = [];
const chat = new ChatSession({ cwd, sessionId: api.sessionId ?? undefined, agent: 'api', model: 'claude-haiku-4-5-20251001', effort: 'medium', deep: true }, (e) => events.push(e));
const waitFor = (pred: () => boolean, ms: number) => new Promise<boolean>((res) => { const t0 = Date.now(); const iv = setInterval(() => { if (pred()) { clearInterval(iv); res(true); } else if (Date.now() - t0 > ms) { clearInterval(iv); res(false); } }, 300); });
const results = () => events.filter((e) => e.kind === 'result') as Extract<ChatEvent, { kind: 'result' }>[];
chat.start();
chat.send(deepPrompt('What is FROBNICATE v3 in this repo, what does the hive say about why it was chosen, and what does the public web say the word "frobnicate" means? Cite sources.'));
must('deep turn finishes within 5 minutes', await waitFor(() => results().length === 1, 300_000));
const tools = events.filter((e) => e.kind === 'ev' && !!e.ev.tool).map((e) => (e as Extract<ChatEvent, { kind: 'ev' }>).ev.tool as string);
console.log('  tools:', [...new Set(tools)].join(', '));
must('fanned out: subagent, hive search and the web', tools.includes('Agent') && tools.includes('mcp__anthive__project_search') && tools.includes('WebSearch'));
must('subagent progress reached the stream', events.some((e) => e.kind === 'ev' && e.ev.sidechain));
must('nothing was denied', results()[0]!.denials.length === 0);
console.log('  denials:', results()[0]!.denials.join(', ') || 'none');
const notes = await store.list('note');
const report = notes.find((n) => n.title.startsWith('research:'));
must('the report is a note linked to the agent', !!report && report.acl.includes('api'));
must('the report cites the repo, the hive and the web', !!report && /README\.md/.test(report.body) && /note:\/\//.test(report.body) && /https?:\/\//.test(report.body));
must('the answer names the note', !!report && results()[0]!.text.includes(report.id));
console.log('  answer:', results()[0]!.text.slice(0, 200).replace(/\n/g, ' '));
chat.stop();
console.log(`\ncost: $${chat.cost.toFixed(3)}`);
console.log(fails ? `${fails} failure(s)` : 'all green');
process.exit(fails ? 1 : 0);
