import { diffLines, hunksOf } from '../src/tui/diff.ts';
import { Ev } from '../src/core/sessions.ts';
let fails = 0;
const must = (l: string, c: boolean) => { console.log(c ? `✓ ${l}` : `✗ ${l}`); if (!c) fails++; };
const d = diffLines('a\nb\nc\nd', 'a\nx\nc\nd\ne');
must('linhas iguais ficam, trocada vira −/+', d.map((l) => l.kind[0]).join('') === 'sdasda' || d.map((l) => l.kind).join(',') === 'same,del,add,same,same,add');
must('conteúdo certo', d.find((l) => l.kind === 'del')?.text === 'b' && d.filter((l) => l.kind === 'add').map((l) => l.text).join() === 'x,e');
must('iguais não geram mudança', diffLines('k\nk', 'k\nk').every((l) => l.kind === 'same'));
const ev = (tool: string, input: any): Ev => ({ uuid: 'u', parent: null, sidechain: false, type: 'assistant', ts: 0, role: 'assistant', text: '', tool, input });
const e = hunksOf(ev('Edit', { file_path: '/p/a.ts', old_string: 'foo()\nbar()', new_string: 'foo()\nbaz()' }));
must('Edit vira um hunk com −bar +baz', e.length === 1 && e[0]!.lines.some((l) => l.kind === 'del' && l.text === 'bar()') && e[0]!.lines.some((l) => l.kind === 'add' && l.text === 'baz()'));
const w = hunksOf(ev('Write', { file_path: '/p/b.ts', content: 'x\ny\n' }));
must('Write é tudo novo', w[0]!.lines.length === 2 && w[0]!.lines.every((l) => l.kind === 'add'));
const m = hunksOf(ev('MultiEdit', { file_path: '/p/c.ts', edits: [{ old_string: 'a', new_string: 'b' }, { old_string: 'c', new_string: 'd' }] }));
must('MultiEdit vira dois hunks', m.length === 2);
const big = hunksOf(ev('Edit', undefined as any));
must('sem entrada guardada: explica em vez de quebrar', big[0]!.note?.includes('grande') === true);
console.log(fails ? `\n${fails} falha(s)` : '\ntudo verde');
process.exit(fails ? 1 : 0);
